### ISSUE TITLE
Create twitter service

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost#166]
<details open> 
  <summary>
    <b>Description</b>
  </summary>
   We need to create a twitter module based on the current temporary module, following the provided interface for it.
</details>

<br>

<details> 
  <summary>
    <b>Expected Behavior</b>
  </summary>
  It should have all the properties that a module, described on the interface, has.
</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  Could be needed to create more functionality than we have exposed on the interface. Keep questioning what you have on your module and if it need more or less data. If needed talk with the team to check how we can implement it!

</details>

**Comment by fabiojcp** [comment]
@hxsggsz cara fiquei bem afim de fazer uns testes dessa tal proxy reversa, posso te acompanhar na task?

**Comment by hxsggsz** [comment]
claro vai me ajudar bastante pq eu não sei como faz

**Comment by fabiojcp** [comment]
pf me add na task

**Comment by hxsggsz** [comment]
quando a task https://github.com/Alecell/octopost/issues/188 for feita, será necessário criar uma versão "V2.0" desse módulo que consiste em adicionar a opção de fazer um post com carousel de imagens, foto única e story. Todas essas opções devem estar no tabber interno do módulo, então essa task só poderá ser concluída após a criação do mesmo
