### ISSUE TITLE
Create button "New Account"

### ISSUE THREAD

**Issue by kingjotaro** [devhatt/octopost#172]
<details open> 
  <summary>
    <b>Description</b>
  </summary>
  This component should open a dialog with the option to select a social network and save the corresponding API keys in a document. These saved keys will be used when posting content to the selected social networksomething.
</details>

<details> 
  <summary>
    <b>Visual Information</b>
  </summary>
  
![image](https://github.com/Alecell/octopost/assets/23247383/d144e0d7-f5ae-4fc0-bf08-c4ce07399d06)

</details>

**Comment by alvarogfn** [comment]
![image](https://github.com/Alecell/octopost/assets/62889807/e6b89e7e-f804-45bf-8e93-030162c13a7e)
mim de essa

**Comment by flaviafreirec** [comment]
> ![image](https://user-images.githubusercontent.com/62889807/284573435-e6b89e7e-f804-45bf-8e93-030162c13a7e.png) mim de essa

tá na mãoo
