### ISSUE TITLE
Feedback de erro

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost#176]
_label: [error]_

<details open> 
  <summary>
    <b>Description</b>
  </summary>
  No nosso layout existe uma área de display de erro, precisamos criar esse componente e linka-lo no Zustand. 

</details>

<br>

<details open> 
  <summary>
    <b>Visual information</b>
  </summary>

  ![image](https://github.com/Alecell/octopost/assets/13935760/15c2f6f9-ace1-4274-8163-c91e479962d7)

</details>

**Comment by ShuriCode** [comment]
Eu quero

**Comment by buuninbee** [comment]
eu quero

**Comment by Luiginicoletti** [comment]
Galera, mesma coisa aqui, creio que a Shuri não vai conseguir tocar a task, quem quiser pode mandar um "Eu quero!!!"

**Comment by hxsggsz** [comment]
Eu quero!!!
