### ISSUE TITLE
Sentry

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/octopost#179]
## Integrar Sentry

_label: [error trace]
<br>
assignees: [assignee_username]_

<details open> 
  <summary>
    <b>Description</b>
  </summary>
  Integrar o Sentry ao projeto
</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>

  Link da documentação do [Sentry](https://docs.sentry.io/platforms/javascript/guides/react/?original_referrer=https%3A%2F%2Fsentry.io%2F)
  Essa task é dependente [desta](https://github.com/Alecell/octopost/issues/177)

</details>

**Comment by PiluVitu** [comment]
eu quero!!!
