### ISSUE TITLE
Arrumar configurações do ladle para renderizar as fonts do iconFont

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#181]
## Configurar ladle para renderizar iconFont

<details open> 
  <summary>
    <b>Description</b>
  </summary>
   Tentamos renderizar os iconFonts no ladle para teste e notamos que ele não renderiza.
</details>

<br>

<details> 
  <summary>
    <b>Expected Behavior</b>
  </summary>

![image](https://github.com/Alecell/octopost/assets/17785028/866877ca-beb6-4c17-b7fe-16999e674856)

</details>

<br>

<details> 
  <summary>
    <b>Current Behavior</b>
  </summary>

![image](https://github.com/Alecell/octopost/assets/17785028/78123ae4-9501-4f44-b44c-6aae58a7fba7)

</details>

**Comment by aalmeida00** [comment]
Is blocked by https://github.com/Alecell/octopost/issues/117

**Comment by PiluVitu** [comment]
Eu quero !!!

**Comment by Sherlockzen** [comment]
Eu quero!!!
