### ISSUE TITLE
Tabber interno do módulo

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost#188]
<details open> 
  <summary>
    <b>Description</b>
  </summary>
  
  Os módulo tem multiplos tipos de postagem, já que uma rede social pode ter mais de um tipo de post. Por exemplo instagram que tem story, reel e post. Precisamos de um meio de selecionar o tipo de postagem da rede para que todos os tipos sejam cobertos.

</details>

<br>

<details> 
  <summary>
    <b>Expected Behavior</b>
  </summary>
  
  O usuário pode selecionar o tipo de postagem quando está dentro da aba da rede social.
</details>

<br>

<details> 
  <summary>
    <b>Visual information</b>
  </summary>
  
![image](https://github.com/Alecell/octopost/assets/13935760/6fd06657-5914-4f7f-bfee-0a813ec14c73)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Cada tab tem suas regras especificas, logo deve-se atentar a isso.

</details>

**Comment by leandrokzu** [comment]
Foi mal pessoal, acabei fazendo um pedaço dessa task sem querer quando fui fazer o Tabber(issue #34). A estrutura básica do Tabber Interno tá pronta, ficou faltando  os ajustes finais.

**Comment by ArthurCorreiaBrigido** [comment]
Eu quero!!!

**Comment by PiluVitu** [comment]
alguma att pra daily ?

**Comment by ArthurCorreiaBrigido** [comment]
Fala ai, mano. Eu to dando prioridade a estudar Go, daí por isso, não tenho
conseguido avançar nessa minha issue, talvez seja melhor eu passar ela pra
outra pessoa fazer.

**Comment by PiluVitu** [comment]
Blz

**Comment by DominMFD** [comment]
Eu quero!!!
