### ISSUE TITLE
Pesquisar e adicionar extensão do chat gpt

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost#189]
<details open> 
  <summary>
    <b>Description</b>
  </summary>

   O usuário deve ter um meio de usar extensões pré-codadas nas postagens. Essa extensão de agora é o chatGPT para autocompletar postagens e pedir para que seja criadas _copys_. É necessário entender como anexar o chatGTP **EVITANDO O MÁIXMO POSSIVEL DE CLIQUES**, a pessoa deve poder logar na propria conta do chatGPT e então usa-lo dentro do app.

</details>

<br>

<details> 
  <summary>
    <b>Visual information</b>
  </summary>
  

![image](https://github.com/Alecell/octopost/assets/13935760/53481b9e-2ec4-4388-91b0-b730747fe72b)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Lembre-se de adicionar o botão e todas as fucnionalidade e camadas necessárias para fazer funcionar.
Pode ser necessário usar o _Zustand_, caso seja, chamar nois.

</details>

**Comment by Felipeness** [comment]
De acordo com a minha pesquisa e análise, parece que não é viável realizar essa tarefa da maneira que está sendo pedida atualmente. Além disso, a abordagem proposta parece um pouco complicada e improvisada, de acordo com o que eu encontrei.

Eu acho que seria melhor considerar fazer essa tarefa quando tivermos um sistema de suporte mais adequado, o que pode tornar as coisas mais fáceis. Eu também consultei alguns links que podem ajudar a embasar a minha avaliação:

Referências: 
https://www.youtube.com/watch?v=kRhWqUWJwbc
https://www.youtube.com/watch?v=Cy1AMzxTqH8
https://www.youtube.com/watch?v=lLSJxmb13ec
https://platform.openai.com/docs/guides/text-generation/chat-completions-api

Além disso, aqui estão alguns motivos adicionais para adiar a implementação:

A falta de um sistema de suporte adequado pode realmente dificultar a integração do ChatGPT como autocomplete e talvez não funcione tão bem quanto gostaríamos.

Tentar improvisar uma solução pode levar a problemas de desempenho, confiabilidade e dificuldades de manutenção no longo prazo.

Esperar por um sistema de suporte pode nos ajudar a garantir uma abordagem mais sólida e escalável para alcançar nossos objetivos.
