### ISSUE TITLE
add the typescript plugin for css on project

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#202]
<details open> 
  <summary>
    <b>Description</b>
  </summary>

   there is this plugin to add the intelisense about css and scss class modules that you can find in this [link](https://www.npmjs.com/package/typescript-plugin-css-modules)
on this task your mission is to add this library following their documentation and make it work for scss to.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by Luiginicoletti** [comment]
Galera, acho que a Fla não vai conseguir dar continuidade nessa issue, vou confirmar e quem quiser pegar só comentar "Eu quero!!!"
