### ISSUE TITLE
Vídeo introdutório sobre o octopost

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#204]
## Vídeo introdutório sobre o octopost

<br>
assignees: @Alecell 
 

<details open> 
  <summary>
    <b>Description</b>
  </summary>
  Criar um vídeo explicando mais sobre o projeto e intruduzir novos membros sobre como funciona o projeto, a mentoria e os cargos.
</details>

<br>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)
