### ISSUE TITLE
Upgrade Electron Version for Project Stability

### ISSUE THREAD

**Issue by kingjotaro** [devhatt/octopost#226]
**Describe the feature**
Our project currently relies on a deepweb version of Electron, and it's essential to keep our technology working to help the team and the users.

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)
