### ISSUE TITLE
Bug: O hook de prepare-commit-message interrompe comandos de git commit no terminal 

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#229]
Quando eu vou fazer algum commit no projeto, o hook do husky de prepare-commit-message interrompe o meu comando no terminal. 

Isso acontece mesmo que eu digite a mensagem do commit no formato especificado do conventional commit:
`<type>: <description>`

![image](https://github.com/hatcoders/octopost/assets/62889807/2c3519d7-3bb1-4a59-9a3d-a8ca2c170a83)

E o output no terminal também está com um problema: 
Sempre que eu realizo alguma ação, a mensagem é enviada novamente.

![image](https://github.com/hatcoders/octopost/assets/62889807/2b9f2356-c748-41fe-bb9b-33e94be25642)

Minha sugestão é que seja validada somente o conteúdo da mensagem do commit com o hook `commit-msg` para que ele aceite qualquer forma de fazer commit desde que a mensagem atenda o estilo especificado.

Aqui um material muito bom explicando como configurar de forma que corrija os dois problemas:
https://dev.to/vitordevsp/padronizacao-de-commit-com-commitlint-husky-e-commitizen-3g1n

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by Luiginicoletti** [comment]
Galera, quem quiser só comentar  "Eu quero!!!"

**Comment by alvarogfn** [comment]
Eu quero!!! !!! !!! !!!
