### ISSUE TITLE
Action tracking

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost#235]
**Describe the feature**
Criar um action tracking. 
Precisamos ter noção das ações do usuário no aplicação, quantas vezes é feita e como isso impacta o nosso produto.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  É preciso procurar por uma ferramenta que faça isso e aplica-la no projeto. Essas ferramentas em geral são ferramentas de marketing. É importante sabermos onde o usuário clicou, qual foi a jornada dele até o bounce para que possamos maximizar a eficácia do octopost.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
  Isso permite que possamos melhorar a conversão geral do projeto entendendo onde existem gargalos e otmiza-los
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]
</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
  Existe a possibilidade de que isso possa ser feito com Google Analytics, mas podem haver outras ferramentas no mercado. Por sermos um time de dev pode ser o caso de usarmos Snow Plow
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by aalmeida00** [comment]
@Alecell 

Conheço o hotjar, que captura gratuitamente até 35 sessoes por dia, já é um bom começo né?
https://www.hotjar.com/pricing/

No futuro podemos mudar de plataforma, mas acho essa a melhor do mercado.

**Comment by PiluVitu** [comment]
Eu quero!!!

**Comment by PiluVitu** [comment]
- Snowplow aparentemente necessita de um banco de dados externo para poder analizar os dados
- Google Analytics precisa que o site esteja rodando em algum lugar para poder rodar(Inviável para electron)

**Comment by PiluVitu** [comment]
Aparentemente é necessário pagar para poder conseguir criar um pipiline onde poderemos interir onde nossos dados serão salvos

**Comment by PiluVitu** [comment]
Uma versão comunity existe e é preciso fazer uma configuração pelo [aws usando terraform e postegres](https://docs.snowplow.io/docs/getting-started-on-community-edition/quick-start/)

**Comment by PiluVitu** [comment]
Estou sendo prejudicado, ele não entra com nem um email que eu uso 

![image](https://github.com/devhatt/octopost/assets/69992923/4d755625-7fb2-4955-a64f-0292a764ba32)

**Comment by PiluVitu** [comment]
Issue foi transformada em projeto
