### ISSUE TITLE
Criação do primeiro módulo 

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#237]
**Describe the feature**

Pra que o octopost comece a ganhar cara de octopost, precisamos dar um jeito de fazer um módulo para termos dados para tomar as próximas etapas.

<details open>
  <summary>
    <b>Description</b>
  </summary>
 precisamos entender como implementar a criação dos módulos, discutir sobre e no fim criar um de exemplo usando toda interface de modularização já existente
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by alvarogfn** [comment]
Eu quero!!!
