### ISSUE TITLE
replace yarn to pnpm in this project

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#238]
<details open>
  <summary>
    <b>Description</b>
  </summary>
 replace yarn to pnpm in this project 
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
PNPM is  more faster than other packages managers and our yarn is really slow at the moment

<img width="428" alt="image" src="https://github.com/devhatt/octopost/assets/103784814/e7e98a6d-373b-4dba-9bf3-df925b784fee">

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by Sherlockzen** [comment]
Eu quero!!!
