### ISSUE TITLE
Atualizar Codigo de conduta

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/octopost#246]
Atualizar Codigo de conduta, nas regras do servidor do discord tem regras melhores

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by ArthurCorreiaBrigido** [comment]
Eu quero!!!
