### ISSUE TITLE
Ajustar o grid

### ISSUE THREAD

**Issue by JpBurgarelli** [devhatt/octopost#249]
<details open> 
  <summary>
    <b>Description</b>
  </summary>

   No vídeo a seguir, é possível observar que conforme a visualização da viewport diminui, o "Header" permanece fixo e não diminui conforme esperado. O propósito desta Issue é garantir que ele se torne responsivo e se ajuste de acordo com as mudanças de tamanho da tela.
   Provavelmente, esse erro acontece por conta do MainContent e da Navbar da esquerda.

</details>

<br>

<details> 
  <summary>
    <b>Visual information</b>
  </summary>

https://github.com/devhatt/octopost/assets/30197026/e73a23ea-5dbb-4f33-bd6f-d743c9d4a2cc

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by Felipeness** [comment]
Eu quero!!!
