### ISSUE TITLE
Configurar o stylelint com prettier

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/octopost#253]
Configurar o stylelint com prettier.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Existe alguns bugs que o stylelint nao resolve mais e tem que entrar com o prettier, mas o nosso prettier nao atua em arquivos de estilo, ai o mundo acabou. Alguem pega essa budega pelo amor de deus
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)
