### ISSUE TITLE
Adaptação do Componente Tabber para Versão Mobile com Aba 'All'

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost#259]
**Describe the feature**
Adaptação responsiva do componente tabber de redes sociais para dispositivos móveis, incluindo uma nova aba 'All' exclusiva para esta versão.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  A funcionalidade solicitada é a adaptação do componente tabber da versão desktop para a versão mobile, de forma a manter todas as funcionalidades existentes e adicionar uma nova aba denominada 'All'. Esta aba 'All' agregará funcionalidades presentes fora do tabber na versão desktop, otimizando o uso do espaço na interface móvel e melhorando a experiência do usuário.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
O componente móvel permitirá aos usuários alternar entre diferentes contas de redes sociais de forma independente e acessar a funcionalidade agregada na nova aba 'All', substituindo o main composer no topo da página na versão desktop. Isso beneficia o projeto ao proporcionar uma experiência de usuário coesa e otimizada em dispositivos móveis.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

A implementação deve considerar uma abordagem responsiva, onde o componente se adapte automaticamente à resolução atual, sem a necessidade de uma propriedade `mobile` explícita. Deverá suportar todas as funcionalidades do componente desktop, incluindo a nova aba 'All'. A lógica existente deve ser encapsulada de forma a ser reutilizável entre as versões desktop e mobile.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

  
![image](https://github.com/devhatt/octopost/assets/13935760/38a4518a-4fbd-49d4-b28a-5d71c18fdaef)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Informações adicionais devem incluir detalhes sobre como a aba 'All' será integrada ao fluxo atual do usuário e como ela substituirá funcionalidades específicas do main composer na versão desktop.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by Alecell** [comment]
EU QUERO!!!

**Comment by Alecell** [comment]
EU QUERO!!!

**Comment by geisabitt** [comment]
EU QUERO!!!

**Comment by PiluVitu** [comment]
Alguma att pra daily ?

**Comment by PiluVitu** [comment]
Att pra daily ?

**Comment by geisabitt** [comment]
Não

**Comment by wellington-tinho** [comment]
EU QUERO!!!

**Comment by ViniFerreiraL** [comment]
Fala @wellington-tinho, Ale pediu pra você dar uma olhadinha que ele já revisou, tmj men!!

**Comment by thiagoCalazans-dev** [comment]
cimentado
