### ISSUE TITLE
Ajuste do Main Content para Versão Mobile

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost#260]
**Describe the feature**
Ajustes necessários na versão mobile do componente Main Content para otimizar a usabilidade em dispositivos móveis, removendo algumas funcionalidades da versão desktop.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Adaptação do componente Main Content, que é parte do sistema de gerenciamento de postagens, para a versão mobile. A versão adaptada manterá a funcionalidade principal de entrada de texto e links, mas removerá as opções "Save Draft", calendário e anexo. É importante que o desenvolvedor responsável compreenda a função dos elementos removidos para propor alternativas adequadas ou levantar questões pertinentes em reuniões diárias (dailies).
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Este componente permite aos usuários compor postagens diretamente de seus dispositivos móveis com uma interface simplificada que foca na essencialidade da criação de conteúdo, beneficiando o projeto ao garantir uma experiência de usuário consistente e focada em dispositivos móveis.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

**Importante**: Verificar se será necessário criar um novo componente ou se adaptações no componente existente são suficientes. O componente deve mostrar os limites de caracteres, que já foram implementados, e avaliar a necessidade de um botão de reset de texto. Além disso, precisa-se entender o comportamento ao clicar na engrenagem, possivelmente ajustando ou removendo esta funcionalidade para a versão mobile.
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

  
![image](https://github.com/devhatt/octopost/assets/13935760/78a19c0c-be03-4349-a74f-43707e9a5720)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
**Atenção**: O desenvolvedor deve trabalhar em estreita colaboração com a equipe de design para garantir que todas as funcionalidades e ajustes estejam alinhados com as necessidades dos usuários e com os objetivos do projeto. O componente atualizado deve incluir uma nova aba 'All', exclusiva da versão mobile, que condensa as funcionalidades de composição de postagens.
</details>

**Comment by JpBurgarelli** [comment]
Eu quero!!!
