### ISSUE TITLE
Geração de Releases Automatizadas 

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#271]
**Descreva a feature**
Precisamos criar uma forma de automatizar a geração de releases para os aplicativos em electron.

<details open>
  <summary>
    <b>Description</b>
  </summary>

 Por exemplo, quando Alexandre(nome ficticio) cria uma PR e adiciona novo código na codebase, devemos ter uma forma automatizada de gerar uma versão 0.2.0 para o nosso projeto e adicionar um exe com o electron nas releases. se Alexandra (nome ficticio) criar um novo PR e ele for mergeado, devemos criar uma versão 0.3.0 e assim por diante para mantermos um controle.

</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
  Criar releases contendo o .exe em electron a ser instalável para cada versão lançada no projeto.

</details>

**Comment by alvarogfn** [comment]
eu quero!!!

**Comment by aalmeida00** [comment]
Eu quero!!!

**Comment by alvarogfn** [comment]
EU QUERO!!!
