### ISSUE TITLE
Atualizar as referencias na documentação

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#273]
**Describe the fix**

Em algumas partes da documentação, alguns links estão para o repositório do Alecell (https://github.com/Alecell/octopost).

![image](https://github.com/devhatt/octopost/assets/62889807/274d7841-6974-4e07-ba5a-e8c84c878a36)

O certo é que o link seja para o repositório da devhatt (https://github.com/DevHatt/octopost).

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)
