### ISSUE TITLE
Função para resolver o script.js de cada plugin dado especificado path

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#274]
Pull request deve apontar para #237 

## Função para saber o path do script.js do plugin

É necessário criar uma função/script que resolve arquivos a partir da chave main do package.json. 

Dada tal estrutura de pastas e assinatura de função:
```
plugins/
  plugin-1/
    package.json
  plugin-2/
    package.json
  ...
```
```tsx
const pathToJsProductionFile: string = resolveModulePath('plugins/plugin-1');
```

1. A função resolveModulePath deve ser capaz de encontrar o package.json na raiz da pasta, ou jogar um erro caso não esteja presente.
2. A função resolveModulePath deve ser capaz de pegar o path contido dentro do `main` e juntar com o path passado por parâmetro (_'plugins/plugin-1'_), por exemplo, se o main do package.json está apotando para dist/main.js, o resolveModulePath deve ser capaz de juntar os dois paths e retornar `plugins/plugin-1/dist/main.js`
3. Caso o main não esteja presente, deve jogar um erro.

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)
