### ISSUE TITLE
Função que pega os metadados dos plugins

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#275]
Depende da #274 ser mergeada primeiro e a pull request deve apontar para #237 

## Função para saber o metadado de todos os pacotes

É necessário criar uma função/script que resolve os metadados de cada plugin.

Dada tal estrutura de pastas e assinatura de função:
```
plugins/
  plugin-1/
    package.json
  plugin-2/
    package.json
  ...
```

```tsx
interface PluginMetadata {
  name: string;
  script: string; // Aqui, você pode usar a função resolveModulePath para pegar isso.
  version: string;
  author?: string;
  repository?: string;
  // ...
}

const modulesMetadata: PluginMetadata[] = resolveModulesMetadata('plugins');
```

1. A função resolveModulesMetadata deve ser capaz de encontrar o package.json na raiz da pasta, ou jogar um erro caso não esteja presente.
2. A função resolveModulesMetadata deve ser capaz de pegar o as informações do package.json para gerar um metadata e informar a aplicação dos módulos presentes na aplicação. Caso algum dos campos não opcionais não esteja presente, o módulo deve jogar um erro.

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)
