### ISSUE TITLE
Ajustes técnicos no pacote de orquestrador de módulos

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#277]
A pull request deve apontar para #237 

# Fazer ajustes no pacote de orquestrador de módulos

1. Renomear a pasta no packages de `module-register` para `module-manager` para ficar mais semântico e bater com a lib do npm. 
2. Colocar o nome do projeto no `package.json` como `@octopost/module-manager`.
3. Mover todos os tipos de `src/modules` para a pasta de `types` dentro do pacote e exportar no `index.ts` para expor os tipos para quem for usar.
```tsx
// index.ts
export type { PostModes, Octomodule, /* ... */ } from './types'
```
5. Renomear a classe `octoModule` para `register` e injetar ela no index.ts
```tsx
// index.ts
export const manager = new Manager();

declare global {
  interface Window {
    $$manager: typeof manager;
  }
}

window.$$manager = manager;
``

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by alvarogfn** [comment]
EU QUERO!!!
