### ISSUE TITLE
Integrar os endpoints do express com o orquestrador de módulos

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#278]
Não deve ser pega antes da #275 e a pull request deve apontar para #237 

# Integrar os endpoints do express com o orquestrador de módulos #278

APP - Aplicação
MM - Module-Manager
ESS - Express

* (ESS -> APP) O aplicativo no startup, vai fazer um fetch para a API modulesMetatada e buscar quais são os módulos que devem ser carregados e armazenar no context.
* (APP -> MM) A aplicação deve se comunicar com o module-manager para informar quais módulos devem ser carregados. Você vai no context passar quais são os módulos que vão ser carregados pelo endpoint de `modulesMetadata` atráves do pelo emit('alguma-coisa-carregue-isso', payload).
* (MM -> APP) O MM vai notificar através do `subscribe` qual módulo a aplicação vai carregar, passando o nome, id e source path através do payload do subscribe.  Quando o módulo terminar de carregar, ele vai chamar o próximo módulo da lista. (Isso será usado para exibir uma tela de login bonitinha dps).
* (APP -> ESS) O APP vai chamar um fetch para o endpoint de módulos com o método POST passando a URL, e o sourcePath no payload. 
* (ESS -> APP) O express vai buscar o módulo através do PATH que você passou no payload levando como referencia a pasta documents/octopost/plugins, e retornar o arquivo.
* (APP) Vai transformar a resposta em um blob, criar um script, usar o URL.createObjectURL(blob), colocar o src apontando pra essa URL e injetar no document.head
* (MM -> APP) O próprio módulo vai notificar o MM quando for carregado através do método register, que vai notificar a aplicação para carregar o próximo módulo. Quando todos os módulos forem carregados e adicionados, você emite um evento com o nome de all-modules-loaded ou sei lá, para que a aplicação tire a aba de loading e mostre a interface.

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by PiluVitu** [comment]
Eu quero!!!
