### ISSUE TITLE
Melhorar as regras de eslint para deixar o padrão de código do octopost mais consistente 

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#298]
Precisamos melhorar as regras de eslint do octopost para fortalecer os padrões de código do octopost. 

Isso vai facilitar a escrita de código de forma consistente na aplicação, e também agilizar o processo de code review. 

Por isso, gostaríamos de ouvir as suas sugestões e opiniões sobre quais regras devemos adicionar, modificar ou remover.

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by PiluVitu** [comment]
Alguma att para daily 16/01 ?
