### ISSUE TITLE
Identificação dos Items 

### ISSUE THREAD

**Issue by JpBurgarelli** [devhatt/octopost#305]
<details open>
  <summary>
    <b>Descrição</b>
  </summary>
 Identificar todos os itens, utilizar o componente de ícones para usa-los e identificar aqueles que não estão presentes no componente de ícones. Além disso, verificar quais ícones precisam ser adicionados ao conjunto existente de ícones  .
</details>
<br>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
