### ISSUE TITLE
 Ajustar as opções do Commitizen

### ISSUE THREAD

**Issue by JpBurgarelli** [devhatt/octopost#306]
<details open>
  <summary>
    <b>Description</b>
  </summary>
  [Describe the new feature requested.]
</details>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
