### ISSUE TITLE
Criar/adicionar ícone de "close" pra o modal desktop

### ISSUE THREAD

**Issue by Sherlockzen** [devhatt/octopost#311]
**Describe the feature**
A criação de um ícone de close conforme o design elaborado no figma para uso no componente de modal, na versão desktop.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Ícone em formato de "X" para ser utilizado no botão de fechar modal na versão desktop do app.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  

</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

![image](https://github.com/devhatt/octopost/assets/90076846/265c4ddb-4cde-4b71-b085-05662cb3afc7)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by PiluVitu** [comment]
Depende da do nico 
https://github.com/devhatt/octopost/issues/317

**Comment by Luiginicoletti** [comment]
Issue sendo tratada no pr  #430

**Comment by Sherlockzen** [comment]
Issue resolvida na pr #452
