### ISSUE TITLE
Criar ícone de voltar pra versão mobile

### ISSUE THREAD

**Issue by Sherlockzen** [devhatt/octopost#312]
**Describe the feature**
Criar um ícone de voltar para a versão mobile.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Criar o ícone de voltar/retornar para uso na versão mobile.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Uso do ícone para os botões de "voltar" da versão mobile.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

![image](https://github.com/devhatt/octopost/assets/90076846/d4a6116e-11ac-4be0-bcf8-ee986aec6f41)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by pedromiguelmvs** [comment]
eu quero!!!

**Comment by Luiginicoletti** [comment]
Ícone já foi criado e adicionado ao componente Icon. #392

Segue a forma de utilizá-lo:

1. Importe o componente Icon:
`import Icon from '~components/Icon/Icon';`



2. Use o componente
`<Icon icon="nome-do-icone" />`


3. Atributos adicionais:

```
width={}: Valor inteiro para a largura do ícone.
height={}: Valor inteiro para o comprimento do ícone.
size={}: Valor inteiro para a combinação de largura x comprimento do ícone.
color="": Valor de string para as cores do ícone, seguindo nosso guia de estilo.
```

Uso
![image](https://github.com/devhatt/octopost/assets/17785028/4dfabb23-818a-4575-93de-807d5d32ede7)
![image](https://github.com/devhatt/octopost/assets/17785028/338a5d04-3bf7-413a-8946-7f585d0e9f0f)
![image](https://github.com/devhatt/octopost/assets/17785028/c8d5eaf4-5966-4151-abde-d9f2dffff571)

Certifiquem-se de seguir essas diretrizes ao implementar o novo ícone. Agradecemos pela colaboração!
