### ISSUE TITLE
Criação de ícone de bolinha

### ISSUE THREAD

**Issue by Sherlockzen** [devhatt/octopost#313]
**Describe the feature**
Criar um ícone de bolinha pra o projeto.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Esse ícone será usado na versão desktop e onde mais ser necessário.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  

</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

![image](https://github.com/devhatt/octopost/assets/90076846/65a72337-00d7-47f8-9cfb-bb4dd2c019c7)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  

</details>

**Comment by PiluVitu** [comment]
Depende da do nico #317

**Comment by Alecell** [comment]
Eu quero!!!

**Comment by Luiginicoletti** [comment]
Ícone já foi criado e adicionado ao componente Icon. #392

Segue a forma de utilizá-lo:

1. Importe o componente Icon:
`import Icon from '~components/Icon/Icon';`

2. Use o componente
`<Icon icon="nome-do-icone" />`

3. Atributos adicionais:

```
width={}: Valor inteiro para a largura do ícone.
height={}: Valor inteiro para o comprimento do ícone.
size={}: Valor inteiro para a combinação de largura x comprimento do ícone.
color="": Valor de string para as cores do ícone, seguindo nosso guia de estilo.
```

Uso
![image](https://github.com/devhatt/octopost/assets/17785028/4dfabb23-818a-4575-93de-807d5d32ede7)
![image](https://github.com/devhatt/octopost/assets/17785028/338a5d04-3bf7-413a-8946-7f585d0e9f0f)
![image](https://github.com/devhatt/octopost/assets/17785028/c8d5eaf4-5966-4151-abde-d9f2dffff571)

Certifiquem-se de seguir essas diretrizes ao implementar o novo ícone. Agradecemos pela colaboração!
