### ISSUE TITLE
Criar arquivo codeowners para auto adicionar reviewers nos pull request

### ISSUE THREAD

**Issue by aalmeida00** [devhatt/octopost#314]
**Describe the feature**
Criar arquivo codeowners para auto adicionar reviewers nos pull request

Adicionar a regra * @devhatt (validar se essa regra vai funfar)
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by PiluVitu** [comment]
Alguma att para daily 16/01 ?

**Comment by PiluVitu** [comment]
Alguma att pra daily ?
