### ISSUE TITLE
change path alias

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#316]
**Describe the feature**
change path alias to work with every folder outside `src` folder

<details open>
  <summary>
    <b>Description</b>
  </summary>
  currently the path alias is configured to only work with folder inside de `src` folder
  
![image](https://github.com/devhatt/octopost/assets/103784814/94dd3719-8ec8-4a2c-86b2-2cdca6fdabbb)

- with this task you will have to change it to works in every folder inside this project.
- add the `~electorn/` path alias.
</details>

<br>

<details open> 
  <summary>
    <b>Implementation Details</b>
  </summary>

- you will have to deal with every possible error that this change will do and garantee that all `path alias` existents still works.

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by pedromiguelmvs** [comment]
eu quero

**Comment by PiluVitu** [comment]
Migrar `useSocialNetworkStore.tsx` para usar com os novos módulos, o arquivo se encontra dentro do componente `Tabber`
