### ISSUE TITLE
Atualização do font-icon

### ISSUE THREAD

**Issue by JpBurgarelli** [devhatt/octopost#317]
**Describe the feature**
Atualizar o font-icon para deixar de ser font icon e ser Svg puro

<details open>
  <summary>
    <b>Description</b>
  </summary>
  [Describe the new feature requested.]
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Luiginicoletti** [comment]
Eu quero!!!

**Comment by PiluVitu** [comment]
Alguma att pae pra daily ?

**Comment by PiluVitu** [comment]
att pra daily
