### ISSUE TITLE
transformar o componente maincomposer e composerEditor controlled

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#318]
<details open>
  <summary>
    <b>Description</b>
  </summary>
  atualmente esses dois componentes estão sendo controlados internamente mas isso não faz sentido atualmente na aplicação, essa task é pra mudar isso atualmente.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

necessário que esses componentes sejam controlados por quem usá-lo via props

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by pedromiguelmvs** [comment]
eu quero

**Comment by pedromiguelmvs** [comment]
eu quero!!!

**Comment by PiluVitu** [comment]
Alguma att para daily 16/01 ?

**Comment by pedromiguelmvs** [comment]
@PiluVitu 
Salve! Não consegui estar presente pra daily de hoje, empaquei numa reunião!
Fiz um progresso substancial, finalizei o MainComposer e a previsão para hoje a noite é de pegar o ComposerEditor e estruturar o PR

**Comment by PiluVitu** [comment]
Dalle pae, qualquer coisa abre o pr e bota em draft, parabêns man

**Comment by pedromiguelmvs** [comment]
Perdoa a demora! PR anexado como rascunho
