### ISSUE TITLE
Adicionar typecheck no build e no pre-commit

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#320]
Uma das tarefas pendentes no nosso projeto é fazer o typecheck rodar no código antes de fazer um commit, e antes de fazer o build do projeto. 

1. Adicionar o `tsc` antes do build (já está configurado como noEmit no tsconfig), isso vai adicionar automaticamente o typecheck à pipeline.
2. Criar um script npm que rode o tsc sozinho e esse script deve ser chamado no nosso hook de pre-commit no husky.
3. Corrigir todos os erros decorrentes do comando de tsc

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
