### ISSUE TITLE
[2024-04-01]: create a useKeyPress hook that listen the keyboard, and closes the modal when user presses ESC

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#343]
```
// TODO [2024-04-01]: create a useKeyPress hook that listen the keyboard, and closes the modal when user presses ESC
```

https://github.com/devhatt/octopost/blob/effa108c874c1cec9c99636c31ef0c0c3cffbc96/src/components/Modal/Modal.tsx#L2

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
