### ISSUE TITLE
- Criar um hook de useKeyPress para abstrair a lógica de teclas do teclado

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#344]
Precisamos de um hook que escute sempre que um usuário apertar uma tecla no 

```tsx
export default function App() {
  const [isOpen, setOpen] = React.useState("");

  useKeyPress("Escape", onKeyPress);

  function onKeyPress(e) {
    e.preventDefault();
    setOpen(false);
  }

  return (
    <Modal>
    asdasd
    </Modal>
  );
}
```

Assignees: 
Labels: 
Milestone: 

```
            TODO - Criar um hook de useKeyPress para abstrair a lógica de teclas do teclado
```

https://github.com/devhatt/octopost/blob/effa108c874c1cec9c99636c31ef0c0c3cffbc96/src/components/Modal/Modal.tsx#L39

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
