### ISSUE TITLE
- Criar um hook de useKeyPress para abstrair a lógica de teclas do teclado

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#345]
Precisamos de um hook que escute as teclas especificas pressionadas do teclado e execute callbacks.

Caso de uso:
```tsx
export default function Modal() {
  const [isOpen, setOpen] = React.useState("");

  useKeyPress("Escape", onKeyPress); // vai fechar o modal ao clicar esc

  function onKeyPress(e) {
    e.preventDefault();
    setOpen(false);
  }

  return (
    <Modal isOpen={isOpen}>
    asdasd
    </Modal>
  );
}
```

Assignees: 
Labels: 
Milestone: 

```
            TODO - Criar um hook de useKeyPress para abstrair a lógica de teclas do teclado
```

https://github.com/devhatt/octopost/blob/effa108c874c1cec9c99636c31ef0c0c3cffbc96/src/components/Modal/Modal.tsx#L39

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
