### ISSUE TITLE
Criar um hook de useKeyPress que escuta quando uma tecla é pressionada no teclado

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#346]
O caso de uso do hook seria: 

```tsx
import { useKeyPress } from "~hooks/useKeyPress";

export default function App() {
  const [isOpen, setOpen] = React.useState("");

  useKeyPress("Escape", onKeyPress);

  function onKeyPress(e) {
    e.preventDefault();
    setOpen(false);
  }

  return (
    <Modal isOpen={isOpen}>
    </Modal>
  );
}
```

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
