### ISSUE TITLE
Utilizar o Hook `useKeyPress` para fechar o modal quando a tecla ESCAPE é pressionada.

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#347]
Isso facilitaria para pessoas deficientes visuais que estão no leitor de tela a fechar o modal.

## Não comece essa tarefa antes que a #346 seja mergeada.

https://github.com/devhatt/octopost/blob/effa108c874c1cec9c99636c31ef0c0c3cffbc96/src/components/Modal/Modal.tsx#L1-L58

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
