### ISSUE TITLE
Colocar regra de underscore em variaveis membro e regra de nomeclatura de classe abstrata

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#349]
```
        //  TODO: Colocar regra de underscore em variaveis membro e regra de nomeclatura de classe abstrata
```

https://github.com/devhatt/octopost/blob/effa108c874c1cec9c99636c31ef0c0c3cffbc96/.eslintrc.cjs#L139

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
