### ISSUE TITLE
Externalizar lógica de inicialização do sentry para um arquivo separado

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#353]
Para deixar o nosso arquivo de App.tsx mais limpo, seria bom externalizar a lógica de inicialização do Sentry em um arquivo separado e usa-lo como um componente React no App.tsx

```tsx
import { SentryRoutes } from "./SentrySetup"

const App = () => {
  return (
    <ModuleProvider>
      <div className={scss.app}>
        <Head />
        <Router>
          <SentryRoutes>
            <Route element={<Home />} path="/" />
          </SentryRoutes>
        </Router>
      </div>
    </ModuleProvider>
  )
}
```

https://github.com/devhatt/octopost/blob/effa108c874c1cec9c99636c31ef0c0c3cffbc96/src/App.tsx

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by DominMFD** [comment]
Eu quero!!!
