### ISSUE TITLE
adicionar ícone de minimizar ao invés de utilizar o caractere `-`

### ISSUE THREAD

**Issue by alvarogfn** [devhatt/octopost#354]
O componente de AccordionTab está usando o caractere  de menos `-`  ao invés de um icone do componente `Icon`.

https://github.com/devhatt/octopost/blob/effa108c874c1cec9c99636c31ef0c0c3cffbc96/src/components/AccordionTab/AccordionTab.tsx#L15-L21

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by DominMFD** [comment]
Eu quero!!!

**Comment by Luiginicoletti** [comment]
Issue sendo tratada no pr #430
