### ISSUE TITLE
searching for button não está de acordo com o layout

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#355]
<details open>
  <summary>
    <b>Description</b>
  </summary>
o botão em baixo da barra de pesquisa está fora do padrão do layout do figma, sua missão é ver o que ta diferente e ajustar para seguir o figma
</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

<img width="68" alt="image" src="https://github.com/devhatt/octopost/assets/103784814/c161e577-e739-49a3-8596-fc566b70ce30">

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by alvarogfn** [comment]
eu quero!!!

**Comment by Alecell** [comment]
Essa task não fará parte do MVP
