### ISSUE TITLE
Alinhamento do main content 

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/octopost#356]
**Describe the feature**
A clear and short description of the feature.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  
 Ajustar o main content para que ele se comporte conforme no figma 
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]

</details>

<br>

<details open> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

- Jeito errado: 
![image](https://github.com/devhatt/octopost/assets/69992923/5002df93-1dda-488c-ae64-0e9df6664260)

- Jeito certo 
![image](https://github.com/devhatt/octopost/assets/69992923/c41eebf6-3389-4672-874a-6116264ceaf3)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
