### ISSUE TITLE
mediainput quebrado

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#357]
**Describe the feature**
A clear and short description of the feature.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  quando esse input tem muitas imagens ele quebra para baixo, o comportamento esperado é que ele crie um scroll horizontal para poder mostrar todas as images/videos selecionados.
</details>

<br>

<details open> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

<img width="163" alt="image" src="https://github.com/devhatt/octopost/assets/103784814/cc41d7f7-24e5-4e7d-96b3-8c96c00c2f26">

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
