### ISSUE TITLE
Ajustar o text area 

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/octopost#358]
**Describe the feature**
A clear and short description of the feature.

<details open>
  <summary>
    <b>Description</b>
  </summary>
Ajustar o comportamento da textarea, para que ele ocupe toda a área do container
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>

</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]

</details>

<br>

<details open> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

- Atual 
![image](https://github.com/devhatt/octopost/assets/69992923/20f65185-5cda-47d7-bbcc-f1dd55c25140)

- Correto
![image](https://github.com/devhatt/octopost/assets/69992923/3b9f9230-e919-4652-8eed-5c85789765d4)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Luizefz** [comment]
Eu quero!!!
