### ISSUE TITLE
icones de botões quebrados

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#359]
<details open>
  <summary>
    <b>Description</b>
  </summary>
 ajustar os icones dos botoes do componente de button
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Luiginicoletti** [comment]
Issue sendo tratada no pr #430
