### ISSUE TITLE
Correção de permanência de estado de accordion tabber

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/octopost#360]
**Describe the feature**
A clear and short description of the feature.

<details open>
  <summary>
    <b>Description</b>
  </summary>
 
Imagem quando selecionada:  
![image](https://github.com/devhatt/octopost/assets/69992923/fd917cac-447c-4c8e-8016-2b6595fd46c0)
E o accordion tab é minimizado 
![image](https://github.com/devhatt/octopost/assets/69992923/ad9f0a69-6568-428d-bd8e-bda011ef49ec)

o estado do select de imagens é resetado e isso não deve acontecer 
![image](https://github.com/devhatt/octopost/assets/69992923/11514555-995a-4045-99ca-126e7f1e2835)

</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
