### ISSUE TITLE
Apagar error boundery do ladle

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/octopost#361]
Essa task consiste basicamente em remover o `.story` do componente de `ErrorBoundary`. Este componente não deve ter documentação visual.

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
