### ISSUE TITLE
remover componente home 

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#362]
<details open>
  <summary>
    <b>Description</b>
  </summary>
excluir completamente o componente header do projeto, ele nao será mais usado
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
