### ISSUE TITLE
alinha o texto do componente de input

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#363]
**Describe the feature**
A clear and short description of the feature.

<details open>
  <summary>
    <b>Description</b>
  </summary>
o componente está desalinhado verticalmente por causa da propiedade top, ajustar isso
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
