### ISSUE TITLE
revisar os componentes de preview e de preview container

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#364]
**Describe the feature**
A clear and short description of the feature.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  esses componentes têm muita complexidade para algo muito simples, sua tarefa é revisar esses componentes e refatorar para tirar essa complexidade de dois componentes juntos
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
