### ISSUE TITLE
Ajustar `SocialAccordion`

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#365]
<details open>
  <summary>
    <b>Description</b>
  </summary>

  Os estilos do `socialAccordion` está fora do layout do `figma` pois existem alguns desalinhamentos, sua missão é ajustar para seguir o `figma`

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Felipeness** [comment]
Eu quero!!!
