### ISSUE TITLE
Ajustar logica do searching for para ter um comportamento correto

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/octopost#366]
**Describe the feature**
A clear and short description of the feature.

<details open>
  <summary>
    <b>Description</b>
  </summary>
Corrigir a lógica de quando aparece e sai o searching for

</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]

</details>

<br>

<details open> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Comportamento atual   
![image](https://github.com/devhatt/octopost/assets/69992923/8b4c8e55-26f1-4707-8bc8-73b7584d1e0c)

![image](https://github.com/devhatt/octopost/assets/69992923/088e4937-196f-432d-b797-7bdfbe97b9dd)
</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
