### ISSUE TITLE
Ajustar o tabber stories para se ajustar a nova lógica dos componentes 

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/octopost#367]
**Describe the feature**
A clear and short description of the feature.

<details open>
  <summary>
    <b>Description</b>
  </summary>
 Ajustar a renderização do tabber stories para conseguir renderizar as redes sociais de acordo com os módulos disponiveis
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]

</details>

<br>

<details open> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

![image](https://github.com/devhatt/octopost/assets/69992923/d8181e59-3b8a-41be-b781-8cea7173bdd6)

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
