### ISSUE TITLE
Adicionar props básicas para os componentes

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#368]
**Describe the feature**
A clear and short description of the feature.

<details open>
  <summary>
    <b>Description</b>
  </summary>
adionar props básicas para os componentes de acordo com o html correto, tipo props de aria, funções tipo onChange, necessário implementar a tipagem dos componentes a tipagem `React.ReactComponentWithRef<"div">`
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
dessa forma deixa o componente mais generico e reutilizavel.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
