### ISSUE TITLE
Permitir que o componente checkbox possa ser descontrolado e controlado.

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#369]
Atualmente esse componente é somente _controlled_, necessário refatora-lo para poder deixa-lo _controlled_ e _uncontrolled_, ou seja ele deve aceitar uma `prop` que define o state e, caso não receba nenhuma props, ele deve `togglar` e emitir o novo estado.

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Sherlockzen** [comment]
Eu quero!!!
