### ISSUE TITLE
Refatorar os componentes de preview

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#370]
Atualmente existem dois componentes de preview que fazem a mesma coisa, sua tarefa é **apagar** o componente `Preview` e **renomear** o `ComponentPreview` para somente `Preview`

Tambem deve chamar o componente remanescente no `Tabber`

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by ViniFerreiraL** [comment]
Eu quero!

**Comment by juliaam** [comment]
Eu quero!!!
