### ISSUE TITLE
Refatorar os componentes de media input

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#371]
O componente `InputMedia` e `MediaInput` são redundantes e devem fazer parte do mesmo contexto DDD

- Avaliar se é possível mergear ambos os componentes em um só
- Caso seja necessário deixa-los separados, justificar em um **comentário** o porque eles devem ficar separados.
- Simplificar a lógica caso seja possível
- O uso desse componente está com problemas quando adicionamos uma linha muito comprida de imagens. Busque no projeto pelo uso `<MediaInputs />` e, nesse componente onde ele é chamado, teste adicionando várias imagens em várias resoluções diferentes, é preciso ajustar e garantir que está escalando conforme o tamanho do container e quantidade de imagens. Esse tipo de coisa na imagem abaixo não pode acontecer. 
![image](https://github.com/devhatt/octopost/assets/13935760/d47d7252-fd31-470b-a329-c313ff3cfaf6)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by DominMFD** [comment]
Eu quero!!!
