### ISSUE TITLE
refatorar componentes que fazem algo que outro componente já faz

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#372]
<details open>
  <summary>
    <b>Description</b>
  </summary>
Apagar o savebar e submit button do projeto e colocar o componente de botão já existente necessário no lugar onde o savebar e submit button são usados.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by JpBurgarelli** [comment]
Eu quero!!!
