### ISSUE TITLE
refatorar o enum de httpstatuscode

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#373]
Refatorar o enum de `HttpStatusCode`

- Remover a regra [write-good-comments/write-good-comments](https://github.com/kantord/eslint-plugin-write-good-comments) do eslint
- Atualizar as chamadas do enum para que sejam iguais a declaração `EHttpStatusCode`

**Comment by ViniFerreiraL** [comment]
Eu quero!!!
