### ISSUE TITLE
refatorar o componente feedbackError

### ISSUE THREAD

**Issue by hxsggsz** [devhatt/octopost#374]
Refatorar o componente `FeedbackError`

- Atualizar a lib de icone
- Atualizar o layout de acordo com o novo layout baseado na lista de erros

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
