### ISSUE TITLE
Ajustes no MainComposer 

### ISSUE THREAD

**Issue by JpBurgarelli** [devhatt/octopost#379]
<details open>
  <summary>
    <b>Description</b>
  </summary>
Primeiro, renomear o MainComposer para um nome melhor. Depois, dentro dele, onde há o ComposerEditor, deve-se substituir por um component textarea, dessa forma, haverá a diminuição da complexibilidade desse componente.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
