### ISSUE TITLE
Refatorar o InputSearch

### ISSUE THREAD

**Issue by JpBurgarelli** [devhatt/octopost#380]
Vamos refatorar o `InputSearch` para que ele seja agnostico

- Renomear o componente para um nome mais generico
- Alterar a chamada dos componentes de icone antigo para seguir o novo padrão do componente de icone
- Placeholder vir por `props`
- `iconLeft` e `iconRight` devem ser definidos por props
- Verificar se o componente é hibrido, ou seja, ele deve suportar ser _controlled_ e _uncontrolled_
- O placeholder do texto está desalinhado verticalmente, existe mais espaço em baixo do que em cima, precisa centraliza-los
- Ajustar o tamanho da tag interna, a que possui o padding, ela não está na mesma altura do seu elemento pai
![image](https://github.com/devhatt/octopost/assets/13935760/29a30f17-18ac-4172-a022-d58ccdb4f22c)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
