### ISSUE TITLE
Ajustar Tabber

### ISSUE THREAD

**Issue by JpBurgarelli** [devhatt/octopost#381]
<details open>
  <summary>
    <b>Description</b>
  </summary>
Tabber tem um pau que precisa ser arrumado, mas, tirando isso, precisa ser arrumado. Apagar o mocky stories no taber tambem.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Luiginicoletti** [comment]
Desculpe, não consegui entender completamente. Você poderia explicar melhor a tarefa?
