### ISSUE TITLE
Ajustar os ícones do novo padrão

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/octopost#384]
**Describe the feature**
A clear and short description of the feature.

<details open>
  <summary>
    <b>Description</b>
  </summary>

Ajustar os ícones do modal para que se adequem ao novo padrão dos ícones que o @Luiginicoletti está fazendo
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Luiginicoletti** [comment]
Esta issue requer ajustes antes de prosseguir. 
Para obter mais informações e detalhes sobre os ajustes necessários, por favor, consulte a descrição completa na issue #428. 

Agradecemos antecipadamente pela sua atenção e colaboração para resolver os problemas identificados. Se precisar de mais informações ou esclarecimentos, sinta-se à vontade para perguntar.
