### ISSUE TITLE
Adcionar pacote de tipos do react

### ISSUE THREAD

**Issue by Sherlockzen** [devhatt/octopost#396]
**Describe the bug**
Corrigir a ausência do pacote `@types/react` do projeto, sem ele sempre que alguém clona o repositório e instala as dependências toma erro com o `import React from "react"` por exemplo.

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
