### ISSUE TITLE
Icon Refactors

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#426]
Criei essa issue para referenciar todas as issues referentes a icones.

- [ ] #384 
- [x] #311 
- [x] #312 
- [x] #313 
- [x] #354 
- [ ] #359

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Luiginicoletti** [comment]
Algumas das issues foram solucionadas, no entanto, outras ainda demandam ajustes antes de podermos proceder com a configuração dos ícones.

Abrirei novas issues e marcarei aqui para acompanhar antes de seguir para ajuste dos icones.
