### ISSUE TITLE
Ajustar componente de modal antes de ajustar os icones.

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#428]
**Describe the feature**
[ ] - #384 

<details open>
  <summary>
    <b>Description</b>
  </summary>

Bom dia amigos,

Estou atualizando todos os locais onde os ícones precisam de ajustes.

Antes de realizar as correções nos ícones do modal na issue #384, é necessário ajustar o próprio modal para estar em conformidade com os padrões estabelecidos no nosso Figma. Atualmente, ele parece estar incompleto e fora dos padrões.

Aqui estão algumas diferenças mais evidentes:

- Tamanho dos botões,
- Posicionamento do link com ícone no canto esquerdo inferior,
- Discrepância nas cores de fundo e no cabeçalho do modal.

Estou incluindo uma comparação entre nosso componente atual e o design no Figma para referência.

`Componente atual`
![image](https://github.com/devhatt/octopost/assets/17785028/e8bbfe89-d660-44e0-bbaa-7a744de027a7)

`Componente Figma`
![image](https://github.com/devhatt/octopost/assets/17785028/bc5da4c3-cedd-424d-958c-f949aebebd7e)

Agradeço a atenção e cooperação de todos na busca por uma consistência visual em nossos elementos.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
