### ISSUE TITLE
Ajustar componente de Button antes de ajustar os icones.

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#429]
**Describe the feature**
- [ ] #384 

<details open>
  <summary>
    <b>Description</b>
  </summary>

Bom dia amigos,

Estou atualizando todos os locais onde os ícones precisam de ajustes.

Antes de realizar as correções nos ícones do Button na issue #359, é necessário ajustar o próprio componente para estar em conformidade com os padrões estabelecidos no nosso Figma.

Atualmente, ele parece estar incompleto e fora dos padrões.

Aqui estão algumas diferenças mais evidentes:

- Tamanho dos botões,
- Posicionamento dos icones

Sinto que poderia ser melhorado antes de simplesmente tentar ajustar o icone que use nosso novo componente de icone.

Estou incluindo uma comparação entre nosso componente atual e o design no Figma para referência.

`Componente atual`
![image](https://github.com/devhatt/octopost/assets/17785028/79d0b779-47de-4fb6-b34a-299decd10f34)

`Componente Figma`
![image](https://github.com/devhatt/octopost/assets/17785028/055d1061-25e3-4add-a1af-69863da4426d)

Agradeço a atenção e cooperação de todos na busca por uma consistência visual em nossos elementos.
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by TheGzuckert** [comment]
Eu quero!

**Comment by TheGzuckert** [comment]
Eu quero!!!

**Comment by TheGzuckert** [comment]
Estou quase finalizando a task

![image](https://github.com/devhatt/octopost/assets/83929799/9e4dbf2c-7930-489a-8659-d3cd03ea3ca6)

Entretanto acabei fazendo um pouco a mais do que o necessario para finalizar a task

Acabei mexendo no componente Submit button

![image](https://github.com/devhatt/octopost/assets/83929799/3f41c29f-5d0d-422a-b3fa-ce3bdc277400)
![image](https://github.com/devhatt/octopost/assets/83929799/549eed9c-4d55-453e-86e3-ddc3377ec099)
