### ISSUE TITLE
Ajustar o template de Issue

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/octopost#432]
Ajustar e corrigir os issues templates do projeto.

<details open>
  <summary>
    <b>Description</b>
  </summary>

Atualmente o projeto utiliza o template `.github/pull_request_template.md` pra criação de issues, porém ele é geral e tem componentes tanto para uma feature quanto pra um bug. Precisamos de templates específicos para cada categoria deixando mais organizado pra quem for abrir novas issues.

O projeto já possui 3 templates na pasta `.github/ISSUE_TEMPLATE` , porém o `bug-report.md` está com o mesmo **name:** da `issue_template.md`. A ideia é apagar o `issue_template.md` já que ele é igual ao `bug-report.md`, solucionando o erro.
  
Também é necessário ajustar o `feature-request.md` para que se a issue estiver relacionada com um componente ou algo visual na aplicação ela deve ter uma flag de obrigatoriedade no conceitos visuais pra auxiliar a leitura da issue.

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
