### ISSUE TITLE
Corrigir problemas com componentes no ladle

### ISSUE THREAD

**Issue by Sherlockzen** [devhatt/octopost#434]
## Describe the problem
Quando se usa o ladle tem alguns componentes que não estão funcionando corretamente, ao tentar abrir eles ocorrem alguns erros e não se pode ver os outros componentes até que seja feito um refresh na página.

## Expected Behavior
Usar corretamente o ladle para visualizar os componentes da aplicação de forma individual e testar suas respectivas funcionalidades.

## Current Behavior
Alguns componentes estão quebrando o ladle e impedindo que ele funcione corretamente:
1. Button
2. Compose Editor
3. Feedback error
4. Tabber

## Possible Solution
Verificar os arquivos `.stories.tsx` é provável que algo tenha mudado na aplicação e estes arquivos estejam com algum erro.

## Steps to Reproduce

1. Execute o ladle: `pnpm ladle`
5. Abra os componentes listados acima
6. Verifique os erros no console do navegador

## Extra info or visual elements
![image](https://github.com/devhatt/octopost/assets/90076846/ed008503-bcdf-4a80-9919-029cb34d170c)
![image](https://github.com/devhatt/octopost/assets/90076846/8958db66-bcdc-49b1-9941-d57569d6d469)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
