### ISSUE TITLE
Reajustando os stories do componente Button

### ISSUE THREAD

**Issue by Sherlockzen** [devhatt/octopost#442]
## Describe the bug

Uma PR sobrescreveu as alterações feitas nos stories do Button.

## Description

No PR #412 o arquivo `button.stories.tsx` foi alterado para a sua versão antiga que já tinha sido arrumado no PR #436. Agora é necessário ajustar para a sua atualização correta.

## Steps to Reproduce

Execute `pnpm ladle` para abrir o ladle e verificar o componente de Button.

## Expected Behavior

É esperado novas formas de visualizar o componente com algumas opções que podem ser alteradas por quem utilizar o ladle.

## Current Behavior

Agora se encontra a versão antiga sem essas correções que melhoram a visualização do componente.

## Visual information

[If possible, add screenshots to illustrate this bug.]

## Additional Information

[Provide any additional information, such as relevant versions, browser, OS, context, etc.]

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
