### ISSUE TITLE
teste linear pelo github

### ISSUE THREAD

**Issue by zoldyzdk** [devhatt/octopost#459]
## Describe the feature

[A clear description of the feature.]

## Use Case

[Explain the use for this feature and how it might benefits the project.]

## Implementation Details

[Provide any details or suggestions on how this feature could be implemented.]

## Visual Concepts

**[Does it imply any visual changes to the application? Visual elements are required in the issue]**

## Additional Information

[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
