### ISSUE TITLE
Criar o componente HEADER para o octopost.

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#464]
## Describe the feature

Precisamos criar o HEADER do Octo de acordo com o definido no nosso MVP.

Conforme ja escrito e explicado na print abaixo, construa uma simples NAVBAR com 1 logo a esquerda e as redes sociais da octo a direita.

* Siga o espacamento / padding conforme esta no design do figma. qualquer duvida, estamos a disposicao.

![image](https://github.com/devhatt/octopost/assets/17785028/0d7b53aa-e6b3-4911-b1d3-47a1be89201f)

## Visual Concepts

![image](https://github.com/devhatt/octopost/assets/17785028/eccf7b7a-e84c-42a4-95ba-8d067b5512bf)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by matheus-webp** [comment]
Quero essa task >teteu<

**Comment by matheus-webp** [comment]
Eu quero!!!
