### ISSUE TITLE
Comportamento da barra de busca da sidebar.

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#465]
## Describe the feature

O componente em questão deverá, durante a pesquisa, filtrar os resultados pelo nome do usuário da conta nas redes sociais, separando-os por módulos de conta.

![image](https://github.com/devhatt/octopost/assets/17785028/91b8331b-ab53-4050-8e6e-ed9ac646d2dd)

### Exemplo:
Ao pesquisar alecell, o resultado devera renderizar todas as contas que teriam o nome `alecell` no twitter e facebook.
Caso esses dois se enquadrem na busca, os accordions se mantem na tela enquanto o que foi buscado fizer parte do accordion em questão, na mesma linha de exemplo, caso não tenha a conta alecell no tumblr, esse accordion seria removido na visualização do filtro.

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by JpBurgarelli** [comment]
Eu quero!!!

**Comment by juliaam** [comment]
Eu quero!!!
