### ISSUE TITLE
REMOVER componente SearchClue.

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#466]
## Describe the feature

O componente SearchClue não vai para a versão final, podemos deletar ele e ficar só com a parte do Search

## Use Case

Ao digitar no componente Search

![image](https://github.com/devhatt/octopost/assets/17785028/ff67fd85-704f-48f4-9591-0bcad4a37c3b)

ele renderiza o componente Search Clue

![image](https://github.com/devhatt/octopost/assets/17785028/61d18568-4fca-435e-ac5d-3b162d4c5b45)

Retiraremos esse componente deixando apenas o Search

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
