### ISSUE TITLE
Accordions de redes sociais

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#467]
## Describe the feature

Necessário para poder conseguir separarmos as redes sociais umas das outras e ter uma melhor visibilidade de quais contas fazem parte de qual rede social e tambem caso haja erros.

![image](https://github.com/devhatt/octopost/assets/17785028/998e35c1-dfb0-46fa-b709-ea4ecf33c255)

## Use Case

Quando houver mais de uma conta de facebook por ex, ela devera ir para um acordion.

![image](https://github.com/devhatt/octopost/assets/17785028/fb966b8e-55d0-4269-8f44-d0f4c1d5f6e8)

Caso haja erro em qualquer conta do facebook dentro do acordion, o alertIcon devera aparecer com o accordion minimizado.

![image](https://github.com/devhatt/octopost/assets/17785028/70e921ee-6674-4923-a1df-83696b9f0221)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
