### ISSUE TITLE
Switch de ativação de rede social

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#469]
### Switch de ativação de rede social

- Precisa ter para conseguir selecionar qual rede social será ativada para a mensagem ser enviada para a respectiva conta.

![image](https://github.com/devhatt/octopost/assets/17785028/b90b9d25-d50a-4cb0-a4bd-671b9f32584c)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Alecell** [comment]
eu quero!!!
