### ISSUE TITLE
Favoritar as contas

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#470]
## Describe the feature

Ainda seguindo as features da sidebar, precisamos de um icone para favoritar as contas.

## Use Case

Todas as contas favoritadas serão adicionadas em um novo accordion separado para as contas favoritas, ele vai aparecer sempre ao topo exibindo todas as contas favoritadas por ordem de adição.

- Para essa task deverá ser criado o método de adição
- A troca do icone de estrela de vazado para preenchido
- A criação do acordion de favoritos
- A adição das contas favoritadas nesse acordion novo

## Visual Concepts

![image](https://github.com/devhatt/octopost/assets/17785028/5eeccf45-22e9-429b-b67b-6afea2b4533f)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by uphiago** [comment]
eu quero!!!

**Comment by juliaam** [comment]
Eu quero!!!
