### ISSUE TITLE
New Account

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#471]
## Describe the feature

![image](https://github.com/devhatt/octopost/assets/17785028/b7627f29-5bbe-4e27-8e5b-87174a020089)

É responsável por abrir o modal, onde terá um layout geral de modal, onde clicamos em um dropdown que será onde podemos selecionar a rede social que a conta será vinculada. 

Feito o processo de SSO, a conta deverá ser adicionada no accordion lateral da rede social em questão.

![image](https://github.com/devhatt/octopost/assets/17785028/6fafd391-1ef0-487e-a3c6-73cacc38f806)

Quando uma nova conta for vinculada a uma rede social, essa conta automaticamente ficará ATIVA.

![image](https://github.com/devhatt/octopost/assets/17785028/091fc57d-9334-48cd-8428-1fdf19d2fb46)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by muritadb** [comment]
Eu quero!!!
