### ISSUE TITLE
Main content

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#472]
## Describe the feature

- Duração máxima de midia e tamanho max deverão ser tratados pelo front-end
- O usuário vai ser livre para inserir a quantidade de mídia e texto que ele quiser, o módulo de maneira independe vai fazer o tratamento do limite de texto e midia

![image](https://github.com/devhatt/octopost/assets/17785028/3d216312-0f53-4374-9a30-b8ae1b64430d)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by DominMFD** [comment]
eu quero!!!
