### ISSUE TITLE
asfasfasfasf

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/octopost#478]
## Describe the bug

**[A short description of what the bug is.]**

## Description

[Describe the bug reported.]

## Steps to Reproduce

[If applicable, provide detailed steps to reproduce the bug.]

## Expected Behavior

[Describe what is expected to happen.]

## Current Behavior

[Describe what is currently happening.]

## Visual information

[If possible, add screenshots to illustrate this bug.]

## Additional Information

[Provide any additional information, such as relevant versions, browser, OS, context, etc.]

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
