### ISSUE TITLE
[NOTION] REVAMP README

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/octopost#484]
Puxe umas referencias boas daqui: https://github.com/matiassingers/awesome-readme

E reescreva todos os nossos readme de projetos, isso inclui projetos de sidequest

problema: Nossos readme tão meio confusos e não respondem todas as perguntas do projeto em si e queremos resolver isso
- [ ] **Banner do projeto**
- [ ] **Indice**
- [ ] **Introdução do projeto**
- [ ] **Explicação do projeto**
- [ ] **Como contribuir**
- [ ] **Como rodar o projeto**
- [ ] **Tirar dúvidas**
- [ ] **Regras**
- [ ] **Redes sociais**

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
