### ISSUE TITLE
Arrumar os erros do Error Boundary

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/octopost#486]
## Describe the bug
O Error boundary esta reclamando, necessário corrigir os erros
![image](https://github.com/devhatt/octopost/assets/76929097/65478ae8-b75a-4c78-9974-dce22e0c444a)

## Steps to Reproduce

O error boundary impede que a aplicação crash mas ao tentar buildar você vai receber o erro na tela

## Expected Behavior

A aplicação deve buildar e aparecer a homepage do octopost

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
