### ISSUE TITLE
REMOVER - Widgets

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#487]
## Describe the feature

Remover:

Não terá essas funcionalidades a priori, para economizar tempo de desenvolvimento

## Visual Concepts

![image](https://github.com/devhatt/octopost/assets/17785028/2ff8a7fb-c753-4a47-9d6f-00ba5517a1ef)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
