### ISSUE TITLE
Criação de toast de erro no mobile

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/octopost#489]
## Describe the feature

Criação de novo componente de erro para o mobile 

## Use Case

Quando um erro acontecer na aplicação, ele deve ser mostrado dentro desse toast, exibindo a mensagem retornada no erro 

## Implementation Details

Vai ser necessário a criação de um novo componente baseado no atual `FeedbackError`, crie uma pasta de mobile variation dentro da pasta do `FeedbackError` atual.

## Visual Concepts

![image](https://github.com/devhatt/octopost/assets/69992923/b8f42e5d-8075-44c7-8426-0d8f39e656bc)

## Additional Information

A task **não** se refere a seguinte funcionalidade :
![image](https://github.com/devhatt/octopost/assets/69992923/20756b83-023b-4fb2-81f1-fb274e6149f3)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by thiagoCalazans-dev** [comment]
eu quero!!!
