### ISSUE TITLE
First Comment - REMOVER

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#492]
## Describe the feature

REMOVER

<img width="514" alt="Screenshot 2024-04-28 at 20 07 16" src="https://github.com/devhatt/octopost/assets/17785028/b37e7e3e-d71d-4ff5-8baf-c8b76a153bae">

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
