### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#494]
## Describe the feature

A mensagem responsável por notificar as incompatibilidades que existem, ao fazer uma publicação, deve existir.

<img width="590" alt="Screenshot 2024-04-28 at 20 13 49" src="https://github.com/devhatt/octopost/assets/17785028/9837be97-7d7e-4ee1-a639-4f5de4773141">

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
