### ISSUE TITLE
Save Draft

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#495]
## Describe the feature

REMOVER 

<img width="165" alt="Screenshot 2024-04-28 at 20 14 34" src="https://github.com/devhatt/octopost/assets/17785028/756c132f-3130-4d6a-91d0-c284719e2adb">

Remover tambem
<img width="116" alt="Screenshot 2024-04-28 at 20 15 10" src="https://github.com/devhatt/octopost/assets/17785028/c00bee96-8c1f-4843-ad8d-8f308874e392">

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
