### ISSUE TITLE
Desmonolitização do Projeto

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#499]
## Describe the feature

Atualmente, nosso projeto está estruturado como um monorepo devido à presença de um gerenciador de módulos interno. No entanto, decidimos abandonar o uso desse gerenciador de módulos, o que nos permite reavaliar nossa estrutura de projeto. Esta tarefa tem como objetivo desmonolitizar o projeto, removendo a estrutura de monorepo e reorganizando-o econforme necessário.

## Tarefas:

1. Avaliação da Estrutura Atual:

- Analisar a estrutura atual do monorepo e identificar as dependências entre os diferentes módulos.
- Analisar o que precisa ser apagado tanto como pasta por exemplo: `packages -> module-manager` que contem os arquivos que seriao usados para os módulos e devera ser apagado.
- Apagar tambem `pnpm-workspaces.yaml`

2. Atualização das Referências:

- Certificar-se de que nao haja nenhuma dependência que possa impossibilitar o progresso do projeto.
mesmo que o modulo ainda nao tenha sido implementado, apenas certifique-se de que tudo ficou correto.

3. Testes e Validação: (

- Realizar testes para garantir que a nova estrutura de projeto não introduza regressões ou problemas de dependência.
- Validar a integração contínua para garantir que os fluxos de trabalho de desenvolvimento e implantação continuem funcionando conforme o esperado.

Documentação: 

Atualizar a documentação do projeto caso necessario.

## Implementation Details

[Provide any details or suggestions on how this feature could be implemented.]

## Visual Concepts

Pasta que contem os arquivos do modulo
![image](https://github.com/devhatt/octopost/assets/17785028/6bb87f5a-56a2-4f97-981b-30e875a3faa5)

## Additional Information

Verificar com a equipe a necessidade de excluir essa dependencia (@alvarogfn )
![image](https://github.com/devhatt/octopost/assets/17785028/bfa79afb-47de-4870-b4d9-c4a18870a249)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
