### ISSUE TITLE
Ativar Tab de Postagem

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#502]
## Describe the feature

**Ativação de PostModes:** 

- Implementar a ativação de múltiplos `postModes` simultaneamente para a mesma conta de mídia social. 
_Isso pode envolver ajustes na estrutura de dados e lógica do componente para lidar com múltiplos modos de postagem._

Na sidebar as contas existentes de cada rede social possuem um botão switch cujo ativa ou desativa a conta pra ser usada no post atual.

![image](https://github.com/devhatt/octopost/assets/13935760/9e02ba38-7142-4f20-8202-c5ad50228b9e)

Quando esse switch for clicado a conta em questão será acionada para ser usada como um destino da postagem atual. Com isso ela deverá aparecer no `Tabber` de contas.

![image](https://github.com/devhatt/octopost/assets/13935760/e8d52e92-41fe-4da1-8fc2-1c2ecd637201)

Esse `Tabber` exibe **apenas** as contas ativas para a postagem atual. 

Sua tarefa é:
- Criar uma store de "contas ativas para postagem", essa é uma outra store cuja não é a mesma store do `useSocialmediaStore`
- Atualizar a store usada no `Tabber` para exibir apenas as contas ativas
- Na nova store precisa haver um meio de se comunicar com as contas ativas para que
  - Contas ativadas sejam adicionadas na  lista
  - Contas desativadas sejam removidas da lista

No fim, com sua task completa, deve ser possivel ativar e desativar contas, e, para todas as contas **ativas**, elas serão exibidas no `Tabber`, as contas **desativadas** não aparecerão no `Tabber`

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
