### ISSUE TITLE
Atualizar Estilo do Componente ComposerEditor

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#503]
### Descrição da Tarefa:

Atualmente, o componente `ComposerEditor`possui estilos fixos que fazem com que ele não se expanda conforme a necessidade do uso.
Esta tarefa consiste em tornar o `ComposerEditor` mais flexivel, permitindo assim que ele se estique ou espanda de acordo com o container onde ele está localizado. 
Isso garantirá uma melhor separação de concerns e permitirá uma personalização mais flexível do componente. 
Por exemplo, o componente `ComposerEditor` provavelmente deve ser capaz de receber uma propriedade **className** para sobrescrever alguns de seus estilos padrões.

### Tarefas a serem realizadas:

- Remover o bloco e o container `.textarea` dos estilos e do componente em si no componente `FirstComment`
- Os estilos do componente `ComposerEditor` devem ser mais flexiveis permitindo assim coloca-lo em outros lugares sem exigir refatorar o CSS idealmente
- Caso necessário, criar uma propriedade chamada **className** para o componente `ComposerEditor`, que permitirá a passagem de classes de estilo personalizadas para cada uso. **Isso deve ser evitado, sendo necessário apenas se nao for possivel deixar o componente flexivel com seus proprios estilos**
  - Atualizar a implementação do componente `ComposerEditor` para aplicar os estilos recebidos via **props**.
  - Garantir que os estilos padrão sejam aplicados caso nenhum **className** seja fornecido.
  - Testar o componente para garantir que os estilos podem ser facilmente modificados através da **prop** **className**.
  - Garantir que o componente `ComposerEditor` está funcionando e visualmente correto nos seus 3 usos (first comment, main content e tab content) 

Bloco a ser removido do `FirstComment`
![image](https://github.com/devhatt/octopost/assets/17785028/23e2177b-aa84-4400-9a95-4ac49be5e97a)

### Observações:

Certifique-se de manter a funcionalidade do componente intacta após a atualização dos estilos.

Documente qualquer alteração significativa no código e forneça instruções claras sobre como usar a nova funcionalidade caso necessário!

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by TheGzuckert** [comment]
Eu quero!!!

**Comment by wendesongomes** [comment]
Eu quero!!!
