### ISSUE TITLE
Revisar e Atualizar Testes de ManyInputs (MediaInput.spec.ts)

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#507]
### Descrição: 
Os testes atuais para o componente ManyInputs foram marcados para revisão e correção. Eles envolvem interações com elementos da interface do usuário, como upload de imagens e remoção de imagens. A tarefa é revisar e corrigir os testes conforme necessário para garantir que eles estejam funcionando corretamente e refletindo o comportamento esperado do componente.

### Passos:

**Revisar Cada Teste:**

- Leia cuidadosamente cada teste para entender sua finalidade e comportamento esperado.
- Identifique quaisquer problemas, erros ou áreas que possam exigir atualização.

**Corrigir Seletores:**

- Certifique-se de que os seletores utilizados para interagir com os elementos da interface do usuário estão corretos e são robustos.
- Substitua os seletores que podem ser frágeis por seletores mais robustos, como getByText, getByRole, etc.

**Atualizar Asserts:**

- Verifique se os asserts estão verificando corretamente o comportamento esperado após as interações do usuário.
- Atualize os asserts conforme necessário para refletir com precisão o comportamento esperado.

**Testar Interações:**

- Após as atualizações, execute os testes para garantir que todos estejam passando corretamente.
- Teste as interações do usuário manualmente, se necessário, para garantir que correspondam ao esperado.
- Remover Marcação de Skip:
- Assim que os testes forem revisados e corrigidos, remova a marcação de "skip" para que possam ser executados automaticamente nos próximos test runs.

**Exemplo de Atualização:**

Teste Atual
```
const imageInput = component.getByTestId('imageInput');
await imageInput.setInputFiles('src/assets/logo.png');
```

**Atualização Proposta**
```
const imageInput = component.getByRole('button', { name: 'Upload Image' });
await imageInput.setInputFiles('src/assets/logo.png');
Após a revisão e correção dos testes, certifique-se de que todos os casos estejam passando corretamente e que os testes estejam de acordo com o comportamento esperado do componente ManyInputs.
```

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Alecell** [comment]
eu quero!!!

**Comment by Alecell** [comment]
@DominMFD essa é uma boa task pra vc em sequencia

**Comment by wendesongomes** [comment]
eu quero!!!
