### ISSUE TITLE
Implementar funcionalidade de adicionar conta e refatorar código relacionado (useSocialMedia)

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#508]
### Descrição:

Esta task tem como objetivo implementar a funcionalidade de adicionar uma nova conta de mídia social e refatorar o código relacionado à recuperação de dados das redes sociais. Isso melhorará a funcionalidade e a legibilidade do componente **useSocialMediaStore.**

**Subtarefas:**
Implementar Funcionalidade de Adicionar Conta

**Descrição:** 
Desenvolver a função **addAccount** localizada no `useSocialMediaStore` para permitir a adição de uma nova conta de mídia social ao estado da aplicação.

**Passos:**

- Implementar a função addAccount para adicionar uma nova conta de mídia social ao estado.
- Integrar a função com os serviços externos de mídia social usando o mock de API já presente no projeto
- Atualizar o estado da aplicação com a nova conta adicionada.

**Exemplo de Implementação:**

```
addAccount: async (newAccount: StoreAccount): Promise<void> => {
  // Implementação da lógica para adicionar uma nova conta
  // Atualização do estado com a nova conta
},
```

### Refatorar Lógica de Recuperação de Dados das Redes Sociais

**Descrição:** 
Refatorar o código relacionado à recuperação de dados das redes sociais para melhorar sua legibilidade e eficiência.

**Passos:**

- Identificar e refatorar áreas de complexidade ou baixa legibilidade no código.
- Simplificar e organizar a lógica para torná-la mais compreensível.
- Garantir que a funcionalidade existente não seja comprometida durante a refatoração.

- Refatorar este trecho de código para melhorar a sua organização e clareza
- Remover Filtro Desnecessário na Função de Envio de Posts

**Descrição:** 
Remover um filtro desnecessário na função sendPosts, que exclui posts sem conteúdo antes de enviá-los.

**Passos:**

- Identificar e remover o filtro que verifica a existência de conteúdo nos posts.
- Atualizar a função para processar e enviar todos os posts, independentemente de seu conteúdo.
- Certificar-se de que a remoção do filtro não afete o comportamento esperado da função.

**Observações:**
Cada subtarefa deve ser abordada individualmente e testada para garantir a funcionalidade correta.
Após a implementação e teste de todas as subtarefas, esta task pode ser marcada como concluída no board do GitHub.
Essa abordagem deve proporcionar uma compreensão mais clara do que precisa ser feito e dos passos necessários para cada modificação.

Qualquer duvida consultar a equipe.

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by wendesongomes** [comment]
eu quero!!!
