### ISSUE TITLE
Revisar e Corrigir Testes do Componente SocialAccordion

### ISSUE THREAD

**Issue by Luiginicoletti** [devhatt/octopost#509]
### Descrição:

Esta task consiste em revisar e corrigir os testes do componente **SocialAccordion**, que estão atualmente marcados como falhando. Os testes devem ser revisados para identificar e corrigir os problemas que estão causando as falhas, garantindo que o componente seja renderizado corretamente e que as interações do usuário funcionem conforme o esperado.

**Subtarefas:**
Revisar Testes de Inicialização

**Descrição:** 

- Revisar os testes que verificam o comportamento do componente durante a inicialização para garantir que ele seja renderizado corretamente.

Passos:

- Verificar se o componente é renderizado corretamente durante a inicialização.
- Garantir que os testes estejam verificando adequadamente a presença do componente na tela.

**Exemplo de Verificação:**

- Assegurar que o componente seja renderizado corretamente com base nos parâmetros fornecidos.
- Corrigir Testes de Interação do Usuário

**Descrição:** 
Corrigir os testes que verificam as interações do usuário, como clicar em elementos e verificar mudanças na interface.
**Passos:**

- Identificar e corrigir as interações do usuário que não estão funcionando conforme o esperado.
- Certificar-se de que os elementos clicáveis estão respondendo adequadamente aos cliques do usuário.

**Exemplo de Correção:**

- Garantir que o teste clique no elemento correto e verifique a mudança na interface após a interação.
- Revisar Testes de Listagem de Contas
- Descrição: Revisar os testes que verificam a renderização da lista de contas para garantir que ela seja exibida corretamente.

**Passos:**

- Verificar se a quantidade de contas é exibida corretamente quando a lista está vazia ou contém uma conta.
- Garantir que os testes estejam verificando a presença da quantidade correta de contas na interface.

**Exemplo de Verificação:**

- Confirmar que a quantidade de contas é exibida corretamente com base nos dados de entrada.

**Observações:**

- Cada subtarefa deve ser abordada individualmente, revisando os testes correspondentes e corrigindo os problemas identificados.
- Após a conclusão de cada subtarefa, os testes devem ser executados para garantir que os problemas tenham sido resolvidos e que o componente funcione corretamente.
- Ao marcar esta task como concluída no board do GitHub, inclua comentários sobre as correções realizadas e os testes executados para verificar a funcionalidade do componente.

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Felipeness** [comment]
Eu quero!!!

**Comment by juliaam** [comment]
Eu quero!!!
