### ISSUE TITLE
Integras visualizador de estado

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost#518]
Quando trabalhamos com gerenciadores de estado pode ser bem trabalhoso traquear as alterações de estado. Para isso existem extensões de browser que nos ajudam a traquear esses estados, assim facilitando o debugging!

Essa task consiste em aplicar o Zusty no projeto.
Para saber mais sobre o Zusty leia aqui: https://medium.com/@itsnancyhuang/the-new-zustand-dev-tool-15613144b585

Vale lembrar uma coisa importante, esse tracking do estado **não deve funcionar** em produção, assim é imprescindível que haja validações de ambiente na configuração dessa ferramenta.

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Alecell** [comment]
eu quero!!!

**Comment by brunocroh** [comment]
Eu quero!!

**Comment by brunocroh** [comment]
Eu quero!!!
