### ISSUE TITLE
Ciração de ambiente de stage

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/octopost#521]

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
