### ISSUE TITLE
Sync de conteúdo de media

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost#531]
## Describe the feature

Criar a sincronização entre o conteúdo de mídia do conteúdo principal e o conteúdo de mídia do Post Mode. Atualmente ao selecionar uma mídia no conteúdo principal ela não é selecionada no Post Mode, devemos sincroniza-los para que ao selecionar uma mídia no conteúdo principal a mídia deverá ser selecionada em todos os Post Modes ativos.

## Implementation Details

Devemos sincronizar a mídia adicionada no `MainComposer` para ser adicionada também a todos os `Post Modes` ativos no `Tabber`.

## Visual Concepts

Atualmente está assim: 
![image](https://github.com/devhatt/octopost/assets/134434652/01a28199-9373-4fc7-b3cd-8136ea474c45)

Deve estar assim:
![image](https://github.com/devhatt/octopost/assets/134434652/f755a77c-e0e0-488a-99b7-2e71eae2d04a)
![image](https://github.com/devhatt/octopost/assets/134434652/46b89fe1-1013-421f-94ca-cf220b527bc5)

https://github.com/devhatt/octopost/assets/134434652/78d82ce8-356f-4dc3-a7a6-ec5bd03786e5

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by JpBurgarelli** [comment]
Eu quero!!!
