### ISSUE TITLE
Tabber scroll

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost#532]
## Describe the feature
O Tabber atualmente não tem nenhum modo eficiente de lidar com um número muito grande de abas. Precisamos que o tabber tenha a funcionalidade de scrollar entre as abas, assim como acontece quando temos muitas abas abertas no VSCode para que, independente da quantidade de abas seja possivel ver todas as abas em qualquer resolução de forma facilitada e mantendo a UX.

## Use Case
O usuário precisa ter como scrolar entre as abas pra poder visualizar e usar de forma facil o app mesmo quando tem muitas abas de conta.

## Implementation Details
Essa task é praticamente puramente CSS e HTML, no máximo precisará colocar um evento de scroll lateral, talvez usando GSap para facilitar a leitura do código, mas o cerne da tarefa é estilização e usabilidade.

## Visual Concepts

https://github.com/devhatt/octopost/assets/13935760/2d34a0f8-9f5a-4ebd-acf8-a021dd9bc94a

## Additional Information
O scroll deve funcionar tanto usando o scroll do mouse quanto com swipping

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by juliaam** [comment]
Eu quero!!!
