### ISSUE TITLE
Criação de tela inicial mobile

### ISSUE THREAD

**Issue by Alecell** [devhatt/octopost#533]
## Describe the feature
A tela inicial mobile não está de acordo com o figma. Sua missão é esconder os módulos que não precisam aparecer na versão mobile e fazer a estrutura inicial da página mobile para a adição dos outros componentes.

## Use Case
Fazer o modelo inicial/organização da home mobile.

## Visual Concepts
![image](https://github.com/devhatt/octopost/assets/13935760/d604fef1-85a5-4c66-b557-90d4509bf31a)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by JpBurgarelli** [comment]
Eu quero!!!
