### ISSUE TITLE
Ajuste de Layout do MediaInput

### ISSUE THREAD

**Issue by muritadb** [devhatt/octopost#542]
## Describe the feature
Os botões de midia, tanto quando a mídia é adicionada, quanto o de adicionar midia de fato não estão de acordo com o layout e precisam estar. Quando adicionamos uma imagem e passamos o mouse por cima dessa imagem adicionada no media input existe um "X" para apagar a imagem, esse "X" não está redondo, mas sim ovalado, precisa estar redondo. O botão de adicionar midia está esticado e ele precisa ser menorzinho, sem ser esticado.

## Implementation Details
Cuidado, aparentemente o tamanho do botão de adicionar midia está diretamente ligado ao tamanho do quadradinho de quando a midia em si é adicionada, queremos apenas resolver um problema sem causar outra. Pode ser necessário criar outra classe CSS apenas para o botão de adicionar.

## Visual Concepts
layout:
![image](https://github.com/devhatt/octopost/assets/19556950/e8400486-40a7-4200-a8b7-d941ed5fa75b)

design atual:
![image](https://github.com/devhatt/octopost/assets/19556950/8b758896-8c00-42de-9afa-8e5625f34cee)

## Additional Information

[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by JpBurgarelli** [comment]
Eu quero!!!
