### ISSUE TITLE
Componente Post Mode Identifier

### ISSUE THREAD

**Issue by JpBurgarelli** [devhatt/octopost#543]
## Describe the feature

Esta task é responsável por implementar a funcionalidade e o layout do componente que permite selecionar o modo/tipo de post que desejam publicar em determinada rede. 

Dependendo da rede social, os tipos/modos de post podem variar. Por exemplo, no Instagram, os usuários podem escolher entre diferentes modos de postagem, como reels, stories e etc. 

O objetivo desta task é permitir ao usuário selecionar os post modes para fazer a publicação. Por exemplo, se, dentro do facebook, o usuario quiser fazer a publicao apenas no feed ou no feed e reels, se, no intagram, o usuario quis apenas fazer a publicacao no stories e assim por diante a depender da rede social.

**OBS:** O que está abaixo são/é o(s) nome(s) dos arquivos  do projeto que envolve(m) sua task, para você se situar melhor no desenvolvimento da dela:
- PostModes.tsx

## Implementations Details

Atenção ao fato de que existem 4 opções no PostMode

1- Com o checkbox do PostMode selecionado, ou seja, será postado naquele tipo
![image](https://github.com/devhatt/octopost/assets/35346206/e8debaff-27c1-4c8e-ba0e-280a48569432)

2- Com o PostMode selecionado, para visualização dele
![image](https://github.com/devhatt/octopost/assets/35346206/967e6c22-1be7-481c-a7f3-26ac1b6d783b)

3- Com os dois selecionados, ou seja, você está visualizando ele e será postado nesse tipo
![image](https://github.com/devhatt/octopost/assets/35346206/abf68cb8-6c42-4a38-b8ef-0d5038e2b2f1)

4- Com nenhum selecionado
![image](https://github.com/devhatt/octopost/assets/35346206/7d72d9f2-16d4-4add-a81a-61751a905ea9)

As únicas versões que devem ser levadas em consideração são os tipos acima, esse abaixo da imagem, não deve ser considerado

![image](https://github.com/devhatt/octopost/assets/35346206/805ff1ed-39aa-4b8a-9ca3-43be4a7a7b77)

## Visual Concepts

Na imagem abaixo, usada como exemplo, podemos ver que a publicao sera feita na account_01 da rede social Facebook e o post mode ( tipo de postagem ) 'e um Post apenas, sendo que essa publicao tambem poderia ser feita nos storys e reels, tendo, assim, outros post modes. 
![image](https://github.com/devhatt/octopost/assets/30197026/e4ece294-ce19-4d77-8e15-d864ad5a1520)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by gustavogularte** [comment]
Eu quero!!!
