### ISSUE TITLE
Erro na conta

### ISSUE THREAD

**Issue by muritadb** [devhatt/octopost#544]
## Describe the feature
Para conectar uma conta ao Octopost é preciso uma série de informações que podem expirar em algum momento, portanto ao termino do prazo devemos informar o usuario que existem informações desatualizadas.

Hoje existem poucas coisas que derivam da validação em si, como ainda não sabermos as informações que precisam ser validadas, apenas coloque o `valid: false` em algumas contas do `useSocialMediaStore` para simular um erro.

Depois, baseado nas contas com o `valid: false` aplique o layout de erro no componente em questão.

## Implementation Details
Precisamos de alguma forma fazer apenas que uma ou duas contas possuam erros sem causar problemas, provavelmente podemos fazer isso trabalhando com o mock-api. Pode ser bem interessante colocar uma informação de `valid: false` no `mock-api`, assim levando em consideração o `valid` do mock e remover o `valid: false` que aplicamos no `useSocialMediaStore`.

Vale dizer que, quando uma conta está apresentando erro deve ser **impossivel** de habilita-la no switch, logo, quando uma conta possuir erro, não deve ser possivel ativar o switch.

## Visual Concepts
![image](https://github.com/devhatt/octopost/assets/19556950/549ba797-cca1-4b99-bf84-6636029e35ba)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Frompaje** [comment]
Eu quero!!!
