### ISSUE TITLE
Colocar Icones no componente de limite de caracteres

### ISSUE THREAD

**Issue by JpBurgarelli** [devhatt/octopost#545]
## Describe the feature

Esta task é responsável por aprimorar o componente já existente de limite de caracteres do componente Main Composer, adicionando ícones específicos para cada rede social  ( discord, Twitter, Facebook e etc ). 

Alem de adcionar, esses ícones devem mudar de cor dinamicamente com base no **número de caracteres digitados** pelo usuário e  na **rede social**, pois, a depender da rede social, temos limites diferentes. 

O objetivo é fornecer uma indicação visual clara sobre a proximidade do limite de caracteres permitidos naquela determinada rede social.

**OBS:** O que está abaixo são/é o(s) nome(s) dos arquivos do projeto que envolve(m) sua task, para você se situar melhor no desenvolvimento da dela:

- CharacterLimit.tsx

## Especificações tecnicas
Esse icone já deve estar na store de redes sociais e, dado o modo como o `MainComposer` usa as redes sociais da store, vc deve consumir essa informação para usar o icone. Ele já deve estar presente no objeto `socialMedias`, assim vc precisa apenas pegar o icone que **ja exite** e aplica-lo no componente de forma dinamica, ou seja, derivado da lista de redes sociais, deve exibir os icones em questào.

## Visual Concepts

Como esta
![image](https://github.com/devhatt/octopost/assets/30197026/801bf634-0fe4-451b-968d-e50e5d2f6563)

Como deve ficar:
![image](https://github.com/devhatt/octopost/assets/30197026/f0151f36-71ff-4bfc-9d8f-6430000ada0c)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by oswaldo-oliveira** [comment]
Eu quero!!!

**Comment by gustavogularte** [comment]
eu quero!!!

**Comment by Mathh19** [comment]
Eu quero!!!
