### ISSUE TITLE
Adicionar ícone de erro no accordion

### ISSUE THREAD

**Issue by muritadb** [devhatt/octopost#546]
## Describe the feature

Adicionar ícone de erro no Accordion quando alguma conta possua erro.

## Use Case

O usuário precisa saber se alguma conta está com erro, mesmo com o accordion fechado.

## Implementation Details

As accounts retornadas do useSocialMediaStore possuem o campo `valid` podendo ser true or false, você deve fazer a verificação dessas contas através desse campo, e assim, caso tenha uma conta inválida, adicionar o ícone no Accordion, assim como na imagem.

Ou seja, essa tarefa não tem a responsabilidade de atribuir se a conta é válida ou não, pois isso já está feito. A responsabilidade é de fazer a leitura da informação e atribuir o ícone caso seja o caso.

Se atente ao layout do figma: https://www.figma.com/design/peiX1rvJum4D1RV99Fchqw/Layout-Octo?node-id=54395-66&t=gsLRIgokWXfoK8Ct-0

## Visual Concepts

![image](https://github.com/devhatt/octopost/assets/19556950/71b51655-3401-4f3b-ab77-fe186e5eca52)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by jorge933** [comment]
eu quero!!!
