### ISSUE TITLE
Ajustar layout do Main Content

### ISSUE THREAD

**Issue by muritadb** [devhatt/octopost#547]
## Describe the feature
Os estilos do `AccordionTab` estão ligeiramente fora do layout e precisamos deixa-los perfeitamente de acordo com o layout, assim ajustando alinhamentos, posicionamentos e tamanhos.

## Implementation Details
Lembre-se que esta tarefa **não é apenas** sobre o `Main Content` a pesar de ele ter sido usado como exemplo, esse mesmo componente é usado na `Barra Lateral` também!

Não precisa forçar a barra lateral a ter o botão ou coisas assim, apenas tenha em mente que o componente já está sendo usado em 2 lugares.
![image](https://github.com/devhatt/octopost/assets/13935760/83e268b4-1db7-433e-a44d-e84eb5ae5126)

## Visual Concepts

![image](https://github.com/devhatt/octopost/assets/19556950/326d3a30-4d61-49cc-9499-b545e5f0c307)

![image](https://github.com/devhatt/octopost/assets/19556950/07c131fc-9251-44c4-96b2-8f7335024881)

## Additional Information
Lembre-se de se basear no layout do figma para proporcionalidade de fonte, peso, espaçamento e etc!

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by JpBurgarelli** [comment]
Eu quero!!!
