### ISSUE TITLE
Icone de Setas de Acordion

### ISSUE THREAD

**Issue by JpBurgarelli** [devhatt/octopost#548]
## Describe the feature

Esta task é responsável por aprimorar a funcionalidade do ICONE DE SETAS do Accordion de contas. Atualmente, o ícone de seta é trocado por outro quando o Accordion é clicado. A task visa modificar a estilização para a seta  rotacionar para baixo ao clicar e mudar o estado, proporcionando uma experiência de usuário mais suave e visualmente agradável.

**OBS:** O que está abaixo são/é o(s) nome(s) dos arquivos  do projeto que envolve(m) sua task, para você se situar melhor no desenvolvimento da dela:
- SocialAccordion.tsx - linha 66

## Implementation Details
Essa rotacao deve ser feita com  **apenas** CSS, nao utizando outras libs.

## Visual Concepts

Como esta:
![image](https://github.com/devhatt/octopost/assets/30197026/08a1a559-3e10-4ca9-b96a-41c900b88818)

Como deveria estar
![image](https://github.com/devhatt/octopost/assets/30197026/94ef8507-c10d-4800-a65b-a3e3c878def2)
![image](https://github.com/devhatt/octopost/assets/30197026/47323cca-4955-47b3-b3da-07cf8135bb68)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by JpBurgarelli** [comment]
Eu quero!!!
