### ISSUE TITLE
Componente de troca de dispositivos

### ISSUE THREAD

**Issue by DominMFD** [devhatt/octopost#549]
## Describe the feature

Fazer o layout de componente de troca de dispositivos do preview, ele possui 4 modos, conforme o figma.

## Use Case

O usuário deverá poder escolher o modo que ele deseja ver o preview dele.

## Implementation Details

Essa task não é responsável pelas funcionalidades ao todo, apenas o layout em si e os emits, e deve ser colocada dentro do componente de preview.

## Visual Concepts

![image](https://github.com/devhatt/octopost/assets/35346206/fb4ed24c-56a7-450b-8b75-0ec85d2d5e39)

## Additional Information

Atente-se ao figma do octopost: https://www.figma.com/design/peiX1rvJum4D1RV99Fchqw/Layout-Octo?node-id=54395-66&t=Y80vV9tkPN5OIZ4i-0

Qualquer dúvida falar com @Alecell ou @juliaam ;)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Frompaje** [comment]
Eu quero!!!
