### ISSUE TITLE
Adiconar scroll no side bar

### ISSUE THREAD

**Issue by JpBurgarelli** [devhatt/octopost#551]
## Describe the feature

Esta task é responsável por modificar o comportamento do componente Side Bar (verde)  que contém múltiplos Accordions de contas (vermelho). Quando houver muitos Accordions de contas (vermelho) , a Side Bar (verde) deve permitir a rolagem  (azul) em vez de crescer para baixo indefinidamente. O objetivo é garantir que, quando o número de Accordions de contas ultrapassar o ideal para manter o tamanho da Side Bar, um scroll apareça, melhorando a usabilidade e a organização visual da interface.

**OBS:** O que está abaixo são/é o(s) nome(s) dos arquivos  do projeto que envolve(m) sua task, para você se situar melhor no desenvolvimento da dela:
- SideBar.tsx
- AccordionTab.tsx 
- Accordion.tsx

## Especificaçòes tecnicas
Essa tarefa envolve apenas CSS

## Visual Concepts
![image](https://github.com/devhatt/octopost/assets/30197026/14814161-9e7a-4708-a700-b7e1cd202956)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by Tassio-Med** [comment]
Eu quero!!!

**Comment by Mathh19** [comment]
Eu quero!!!
