### ISSUE TITLE
Criação de script para .env

### ISSUE THREAD

**Issue by juliaam** [devhatt/octopost#564]
## Describe the feature

1 - Criação do script
Haverá um script que consiste em: 
toda vez que for utilizado `pnpm dev`, será verificado se o projeto possui .env. 
Após isso, haverão dois casos de resultado: 

1- ter .env no projeto
2- não ter .env no projeto

Caso aconteça o 1, o deve seguir sua execução normalmente
Caso aconteça o 2, o script deve criar o .env e colocar de forma automática os dados vindo do arquivo de texto que possui as informações para o .env recém criado, e assim, seguir a execução normalmente

2- Criação do modelo do arquivo texto com as informações

Deverá ser criado o arquivo de texto que servirá como base para que o script leia, ele não ficará disponibilizado no projeto, mas sim em  algum outro local, como github, ou algum outro ambiente (ainda não definido).

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by PiluVitu** [comment]
@Alecell O arquivo com as envs base será um .env.example ?
