### ISSUE TITLE
Refatoração de workflows

### ISSUE THREAD

**Issue by PiluVitu** [devhatt/octopost#581]
Atualmente estamos tendo problemas com o workflow (precisamente a de teste e2e) não estar funcionando corretamente, precisamos ver se tem alguma opção de reiniciar elas automaticamente ate umas 2 vezes, ou se o github fornece o contexto do erro e conseguimos implementar uma lógica para quando isso acontecer, a action reiniciar. 

Caso precise deve-se refatorar as actions que podem ter problemas com controle de fluxo

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
