### ISSUE TITLE
Refactor do fluxo de informações de post/account

### ISSUE THREAD

**Issue by juliaam** [devhatt/octopost#582]
## Describe the feature

- Refactor do fluxo de dados de post

## Use Case

Melhorar o ambiente de desenvolvimento para os devs

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)
