### ISSUE TITLE
Tela de registro sem a integração

### ISSUE THREAD

**Issue by juliaam** [devhatt/octopost#597]
## Describe the feature

Essa tarefa tem a responsabilidade de criar a tela de registro, mas sem a funcionalidade do registro em si e sua integração com o back-end. No entanto, todo o resto deve estar pronto, como as validações dos textos do input.

## Use Case

O usuário deverá ter uma tela de registro.

## Implementation Details

Atenção!
O octopost não foi estruturado com o mobile first inicialmente, mas nessa página, será necessário que seja mobile first, seguindo fielmente o design do figma que está disponível nas informações adicionais.
Para facilitar o processo de formulário, você deverá usar o react hook form para criação de formulário, com a validação se ele será emitido ou não com zod.
Esses dois também facilitarão para que você exiba os erros dos campos.
Pode ser que você tenha problemas com a referência no componentes de Input, caso tenha, dê uma olhada nesse vídeo https://www.youtube.com/watch?v=evYPKboKiDs&t=884s

## Visual Concepts

Desktop:

![image](https://github.com/user-attachments/assets/89654919-8008-4def-994e-5a410ee75e32)

Mobile:

![image](https://github.com/user-attachments/assets/28e4bd59-41e0-4598-b032-a6f44bf1e864)

## Additional Information

link do figma: https://www.figma.com/design/peiX1rvJum4D1RV99Fchqw/Layout-Octo?node-id=54395-66

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by lfelipessilva** [comment]
Eu quero!!!

**Comment by juliaam** [comment]
@lfelipessilva consegue falar no discord da devhatt sobre a task?

**Comment by lfelipessilva** [comment]
@juliaam consigo, to na call lá agora
