### ISSUE TITLE
Sincronização do componente ActionBar com a Sidebar e ajuste no layout do mesmo.

### ISSUE THREAD

**Issue by JpBurgarelli** [devhatt/octopost#610]
## Describe the feature
1 - Ajustar o componente ActionBar para que ele fique igual ao do Figma visualmente falando. 
2 - Quando não tivermos contas selecionadas/ativas no componente SideBar (imagem em amarelo), o componente actionBar deve ficar com o botao branco/cinza (imagem circulada em azul). Quando tivermos contas selecionadas, deve ficar roxo, conforme circulado em vermelho.

![image](https://github.com/user-attachments/assets/6415ca74-8803-46fa-af1f-5531fbc7e127)

![image](https://github.com/user-attachments/assets/9accec33-8fcd-4fe0-ac99-8a18c3d736c2)

## Visual Concepts
![image](https://github.com/user-attachments/assets/eede79d0-dded-485c-8b82-9d20edf855ba)

## Additional Information

[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by lfelipessilva** [comment]
Eu quero!!!
