### ISSUE TITLE
Ajuste no layout do tabber

### ISSUE THREAD

**Issue by juliaam** [devhatt/octopost#614]
## Describe the bug

O layout do tabber para uma tela menor que < ou = a 1286px está quebrando.

## Steps to Reproduce

Redimensione a tela para ser menor que 1286, assim o componente do tabber quebrará. 

## Expected Behavior

É necessário que o css seja responsivo a telas menores, não necessariamente para telefones e tablets, e sim para qualquer tamanho

## Visual information

![image](https://github.com/user-attachments/assets/ff9bc7b7-f6d9-45f4-947c-f63cc03a331b)
![image](https://github.com/user-attachments/assets/b6bb0d47-5fb5-4286-85eb-5df1f3947983)

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)

**Comment by JpBurgarelli** [comment]
Eu quero!!!
